version: '3'

services:

  # Homarr
  homarr:
    container_name: homarr
    image: ghcr.io/ajnart/homarr:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock # Optional, only if you want docker integration
      - /srv/homarr/configs:/app/data/configs
      - /srv/homarr/icons:/app/public/icons
      - /srv/homarr/data:/data
    ports:
      - '7575:7575'

  # Portainer
  portainer:
    container_name: portainer
    image: portainer/portainer-ce:latest
    restart: unless-stopped
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    ports:
      - '9443:9443'

  # Jellyfin
  jellyfin:
    container_name: jellyfin
    image: jellyfin/jellyfin:latest
    restart: unless-stopped
    volumes:
      - /srv/jellyfin/config:/config
      - /srv/jellyfin/cache:/cache
      - /media:/media
    ports:
      - '8096:8096'

  # Minecraft Server
  minecraft-server:
    container_name: minecraft-server
    image: itzg/minecraft-server:latest
    restart: unless-stopped
    ports:
      - '25565:25565'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /srv/minecraft-server:/data
      - /srv/minecraft-server/mods:/mods:ro
    environment:
      EULA: TRUE
      TYPE: FORGE
      VERSION: 1.20.1
      DEBUG: TRUE
      SNOOPER_ENABLED: FALSE
      ONLINE_MODE: FALSE
      SERVER_NAME: My Server :-)
      MOTD: Come on in!
      #WORLD: /srv/minecraft-server/world
      ENABLE_COMMAND_BLOCK: TRUE
      ICON: https://upload.wikimedia.org/wikipedia/commons/thumb/d/d8/Minecraft_cube.svg/640px-Minecraft_cube.svg.png
      MAX_PLAYERS: 10
      ENABLE_WHITELIST: FALSE
      #WHITELIST: Player
      RCON_CMDS_STARTUP: /say Server online.
      RCON_CMDS_ON_CONNECT: /say Hello!
      RCON_CMDS_ON_DISCONNECT: /say Goodbye!
      RCON_CMDS_FIRST_CONNECT: /say Welcome!
      RCON_CMDS_LAST_DISCONNECT: /say Server shutdown.

volumes:

  # Portainer
  portainer_data:
    external: true

